# Generated by Django 3.2.21 on 2023-09-27 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230927_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pgi_certificate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='players',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('pgi_certificate', models.CharField(blank=True, max_length=254, null=True)),
                ('players', models.PositiveIntegerField(null=True)),
                ('colour', models.CharField(max_length=100, null=True)),
                ('manufacturer', models.CharField(max_length=254, null=True)),
                ('storage', models.CharField(max_length=254, null=True)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
                ('developer', models.CharField(max_length=254, null=True)),
                ('publisher', models.CharField(max_length=254, null=True)),
                ('pgi_certificate', models.CharField(blank=True, max_length=254, null=True)),
                ('players', models.PositiveIntegerField(null=True)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('RPG', 'Role-Playing Game'), ('Simulation', 'Simulation'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('Puzzle', 'Puzzle'), ('Platformer', 'Platformer'), ('Fighting', 'Fighting'), ('Horror', 'Horror')], max_length=50, null=True)),
            ],
            bases=('products.product',),
        ),
    ]
