# Generated by Django 3.2.21 on 2023-10-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_friendly_name_category_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('Playstation_one', 'Playstation One'), ('Playstation_two', 'Playstation Two'), ('Playstation_portable', 'Playstation Portable (PSP)'), ('Nintendo_snes', 'Super Nintendo (SNES)'), ('Nintendo_64', 'Nintendo 64'), ('Nintendo_gamecube', 'Nintendo GameCube'), ('Sega_genesis', 'Sega Genesis'), ('Gameboy_advanced', 'Gameboy Advanced')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('RPG', 'Role-Playing Game'), ('Simulation', 'Simulation'), ('Strategy', 'Strategy'), ('Sports', 'Sports'), ('Puzzle', 'Puzzle'), ('Platformer', 'Platformer'), ('Fighting', 'Fighting'), ('Horror', 'Horror'), ('Racing', 'Racing')], max_length=50, null=True),
        ),
    ]
