# Generated by Django 3.2.21 on 2023-10-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231002_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='console',
            name='pgi_certificate',
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
