# Generated by Django 3.2.21 on 2023-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20231002_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='console',
            name='players',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='product',
            name='players',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
