# Generated by Django 3.2.21 on 2023-10-11 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20231003_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='associated_console',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.console'),
        ),
    ]
