# Generated by Django 3.2.21 on 2023-10-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_game_associated_console'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='associated_console',
        ),
    ]
